# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MappingTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MappingTask
	pod 'ObjectMapper', '~> 3.5'
	

end
